server:
  port: 8081
spring:
  application:
    name: piana-inquiry-endpoint
  messages:
    basename: messages/endpoint-messages
  datasource:
    url: 'jdbc:postgresql://localhost:15433/piana_inquiry_db'
    username: 'user'
    password: 'pass'
    driverClassName: 'org.postgresql.Driver'
    hikari:
      maximum-pool-size: 40
piana:
  scheduler:
    enabled: true
    endpoint:
      readyToStart: true
      schedulerLockName: 'EndpointManagerJob'
      periodUnit: "Seconds"
  tools:
    internal-client:
      enabled: false

    nats:
      enabled: true
      url: 'nats://localhost:4222'
      status: 'enable'

    redis-cache:
      enabled: true
      sentinel: true
      sentinels: 'localhost:26379,localhost:26380,localhost:26381'
      master: 'oidc-redis-master'
      prefix: 'piana.inquiry'