server:
  port: 9000
piana:
  tools:
    endpoint-solution:
      enabled: true
      endpoints:
        - sample1
        - sample2
      services:
        - insurance_vehicle_third_party_inquiry
spring:
  application:
    name: sample-starter
  messages:
    basename: messages/endpoint-messages
  datasource:
    url: 'jdbc:postgresql://localhost:15433/sample_starter_db'
    username: 'user'
    password: 'pass'
    driverClassName: 'org.postgresql.Driver'
    hikari:
      maximum-pool-size: 40

  flyway:
    enabled: false