server:
  port: 8081
spring:
  application:
    name: piana-inquiry-endpoint
  messages:
    basename: messages/endpoint-messages
  datasource:
    url: 'jdbc:postgresql://localhost:15433/piana_inquiry_db'
    username: 'user'
    password: 'pass'
    driverClassName: 'org.postgresql.Driver'
    hikari:
      maximum-pool-size: 40
piana:
  scheduler:
    enabled: true
    endpoint:
      readyToStart: true
      schedulerLockName: 'EndpointManagerJob'
      periodUnit: "Seconds"
  tools:
    nats:
      url: 'nats://localhost:4222'
      status: 'enable'